name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle and Build
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar-file
          path: build/libs/*.jar
