name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Remove local java.home from gradle.properties
        run: |
          if [ -f gradle.properties ]; then
            sed -i '/org.gradle.java.home/d' gradle.properties
          fi
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: true
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Execute Gradle Build
        run: ./gradlew build --scan

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppleExtended-forge1.12.2
          path: |
            build/libs/*.jar
            cr/build/libs/*.jar